const icons={systems:'<rect x="4" y="3" width="24" height="10" rx="2"/><rect x="4" y="19" width="24" height="10" rx="2"/><path d="M8 8h1m4 0h10M8 24h1m4 0h10M16 13v6"/>',cloud:'<path d="M8 25a6 6 0 0 1-1-12 9 9 0 0 1 17-2 7 7 0 0 1 0 14Z"/>',document:'<path d="M7 3h13l6 6v20H7ZM20 3v7h6M11 15h11M11 20h11M11 25h7"/>',code:'<path d="m9 7-7 9 7 9m14-18 7 9-7 9M19 4l-6 24"/>',automation:'<circle cx="16" cy="16" r="6"/><path d="M13 3h6l1 4 4 2 4-1 3 5-3 3v4l3 3-3 5-4-1-4 2-1 4h-6l-1-4-4-2-4 1-3-5 3-3v-4l-3-3 3-5 4 1 4-2Z" transform="translate(2 0) scale(.85)"/>',tools:'<path d="m21 4-5 5 2 5 5 2 5-5a9 9 0 0 1-12 12L7 30l-5-5 9-9A9 9 0 0 1 21 4Z"/>',book:'<path d="M16 7C12 3 6 4 2 5v23c5-2 10-1 14 2 4-3 9-4 14-2V5c-4-1-10-2-14 2Zm0 0v23"/>',puzzle:'<path d="M12 5V3a4 4 0 0 1 8 0v2h7v8h-2a3 3 0 1 0 0 6h2v8h-8v-2a3 3 0 1 0-6 0v2H5v-8H3a3 3 0 1 1 0-6h2V5Z" transform="translate(2 2) scale(.9)"/>',game:'<path d="M9 9h14c5 0 6 5 7 13s-4 7-8 1H10c-4 6-9 7-8-1S4 9 9 9Z M9 13v8m-4-4h8m10-3h.1m3 5h.1"/>'};
const discoveries=[
{id:'systems',title:'Linux & Networks',tags:'Systems · Networking · Security',icon:'systems',context:'UMBC Training Centers · NiSUS',paragraphs:['Administered Linux systems and AWS training environments, then helped modernize an office network with UniFi and VLAN segmentation.','My background includes Linux administration, Windows Server, AWS, and NIST 800-171 / CMMC compliance work.']},
{id:'cloud',title:'AWS Infrastructure',tags:'Cloud · Operations · Security',icon:'cloud',context:'Professional experience · NiSUS',paragraphs:['Managed AWS infrastructure across EC2, VPC, IAM, S3, WorkSpaces, Security Hub, and Organizations.','Designed an AWS Landing Zone using Organizations and Control Tower for a CMMC engagement, for an affiliate company.']},
{id:'iac',title:'Infrastructure as Code',tags:'Terraform · OpenTofu · AWS',icon:'document',context:'Professional experience · NiSUS',paragraphs:['Deployed and maintained self-hosted GitLab CE and Coder development environments on AWS using Terraform/OpenTofu.','Kept infrastructure and documentation in version control, with branching strategies and merge workflows that make changes easier to review and reproduce.']},
{id:'scripting',title:'Scripting',tags:'Bash · Python · PowerShell',icon:'code',context:'UMBC Training Centers · NiSUS',paragraphs:['Automated virtual training-lab creation and remote deployment using Bash, PowerShell, and VirtualBox.','Developed Python scripts for hardware automation, troubleshooting, and platform integration. I use Python, Bash, and PowerShell regularly.']},
{id:'delivery',title:'WorkSpaces Automation',tags:'CI/CD · Images · Deployment',icon:'automation',context:'Professional experience · NiSUS',paragraphs:['Built an Amazon WorkSpaces patching pipeline and custom bundle builder that produces weekly golden-image rebuilds with zero manual intervention.','Automated Security Hub findings into Jira tickets using EventBridge, making vulnerability triage part of the team’s workflow.']},
{id:'tooling',title:'GitLab & Coder',tags:'GitLab · Coder · Enablement',icon:'tools',context:'Professional experience · NiSUS',paragraphs:['Provided self-hosted GitLab and containerized development environments, and authored an onboarding guide for Git, SSH, branching, and OpenTofu workflows.','Created 725+ Confluence pages of procedures, troubleshooting guidance, and onboarding material to make complex systems easier to use and maintain.']},
{id:'software',title:'Software Development',tags:'JavaScript · Python · Testing',icon:'book',context:'Paygevity · Coursework · Freelance',paragraphs:['Contributed to application deployments and bug fixes across Node.js, Python, JavaScript, and Vue.js as a software engineering intern at Paygevity.','Wrote Cypress regression tests, studied programming in Java and Python, and collaborated on freelance web projects with HTML, CSS, JavaScript, and Firebase.']},
{id:'enigma',title:'Enigma Simulation',tags:'Godot · GDScript · Raspberry Pi',icon:'puzzle',context:'Professional experience · NiSUS',paragraphs:['Co-developed an interactive Enigma simulation for the National Cryptologic Foundation’s mobile escape room.','I handled Raspberry Pi hardware integration and kiosk deployment, and collaborated in Agile sprints using Jira and GitHub.']},
{id:'games',title:'Game Development',tags:'Godot · C++ · Modding',icon:'game',learning:true,context:'Currently exploring · Personal projects',paragraphs:['Exploring procedural generation, physics, and UI systems in Godot and GDScript, while beginning to study C++.','Experimenting with custom gameplay modifications for Civilization VI and VII. These projects are learning exercises and have not yet been published.']}
];
const icon=name=>`<span class="icon" aria-hidden="true"><svg viewBox="0 0 32 32">${icons[name]}</svg></span>`;
const nodes=document.querySelector('#nodes');
nodes.innerHTML=discoveries.map(d=>`<button class="node${d.learning?' learning':''}" data-id="${d.id}" aria-pressed="false" aria-controls="detail">${icon(d.icon)}<span><span class="node-title">${d.title}</span><span class="meta">${d.tags}</span>${d.learning?'<span class="meta">Currently exploring</span>':''}</span></button>`).join('');
function selectDiscovery(id){const d=discoveries.find(d=>d.id===id);if(!d)return;document.querySelectorAll('.node').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.id===id)));document.querySelector('#detail').innerHTML=`${icon(d.icon)}<h3>${d.title}</h3><div class="tags">${d.tags}</div><div class="detail-copy">${d.paragraphs.map(p=>`<p>${p}</p>`).join('')}</div><div class="context">${d.context}</div><div class="detail-rule" aria-hidden="true">◇</div>`;}
nodes.addEventListener('click',e=>{const n=e.target.closest('.node');if(n)selectDiscovery(n.dataset.id)});
nodes.addEventListener('keydown',e=>{const current=e.target.closest('.node');if(!current)return;const buttons=[...nodes.querySelectorAll('.node')];const offsets={ArrowRight:1,ArrowLeft:-1,ArrowDown:3,ArrowUp:-3};if(!(e.key in offsets))return;e.preventDefault();buttons[Math.max(0,Math.min(buttons.length-1,buttons.indexOf(current)+offsets[e.key]))].focus()});
selectDiscovery('enigma');
const resume=document.querySelector('#resume'),resumeButton=document.querySelector('#resume-button');
resumeButton.addEventListener('click',()=>{resume.hidden=!resume.hidden;resumeButton.setAttribute('aria-expanded',String(!resume.hidden));if(!resume.hidden)resume.scrollIntoView({block:'start'});});
document.querySelector('#back').addEventListener('click',()=>{resume.hidden=true;resumeButton.setAttribute('aria-expanded','false');resumeButton.focus();document.querySelector('#tree').scrollIntoView({block:'start'});});
const profile=document.querySelector('#profile');document.querySelector('#profile-button').addEventListener('click',()=>profile.showModal());document.querySelector('#close-profile').addEventListener('click',()=>profile.close());profile.addEventListener('click',e=>{if(e.target===profile){const r=profile.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)profile.close();}});

// Connections represent related skills applied together, not locked prerequisites.
const positions={systems:[48,40],scripting:[48,225],software:[48,410],cloud:[350,40],iac:[652,40],delivery:[652,225],tooling:[954,130],enigma:[350,410],games:[954,410]};
const edges=[['systems','cloud'],['cloud','iac'],['scripting','iac'],['scripting','delivery'],['cloud','delivery'],['iac','tooling'],['delivery','tooling'],['software','enigma'],['scripting','enigma'],['enigma','games'],['software','games']];
document.querySelector('.eras').innerHTML='<span>Foundations</span><span>Applied skills</span><span>Automation</span><span>Tools & development</span>';
for(const button of nodes.querySelectorAll('.node')){const [x,y]=positions[button.dataset.id];button.style.setProperty('--x',x+'px');button.style.setProperty('--y',y+'px');button.insertAdjacentHTML('beforeend',`<span class="node-state" aria-hidden="true">${button.dataset.id==='games'?'IN PROGRESS':'EXPERIENCE'}</span>`);}
const svgNS='http://www.w3.org/2000/svg';const connections=document.createElementNS(svgNS,'svg');connections.classList.add('connections');connections.setAttribute('viewBox','0 0 1220 570');connections.setAttribute('aria-hidden','true');connections.innerHTML='<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 1 L 9 5 L 0 9" style="stroke:#b6a27b;stroke-width:1.5;fill:none"/></marker></defs>';
for(const [from,to] of edges){const [sx,sy]=positions[from],[tx,ty]=positions[to];const x1=sx+240,y1=sy+50,x2=tx-24,y2=ty+50;const path=document.createElementNS(svgNS,'path');let route;if(from==='software'&&to==='games'){route=`M ${x1} ${y1} H ${x1+15} V 548 H ${x2-25} V ${y2} H ${x2}`;}else{const mid=x1+(x2-x1)*.5;route=`M ${x1} ${y1} H ${mid} V ${y2} H ${x2}`;}path.setAttribute('d',route);path.setAttribute('marker-end','url(#arrow)');path.dataset.from=from;path.dataset.to=to;connections.append(path);}nodes.prepend(connections);
function highlightRoute(id){const related=new Set([id]);let changed=true;while(changed){changed=false;for(const [from,to] of edges){if(related.has(to)&&!related.has(from)){related.add(from);changed=true;}}}for(const path of connections.querySelectorAll('path[data-from]'))path.classList.toggle('highlight',related.has(path.dataset.from)&&related.has(path.dataset.to));for(const button of nodes.querySelectorAll('.node'))button.classList.toggle('ancestor',related.has(button.dataset.id)&&button.dataset.id!==id);}
nodes.addEventListener('click',e=>{const button=e.target.closest('.node');if(button)highlightRoute(button.dataset.id)});highlightRoute('enigma');
const help=document.createElement('p');help.className='tree-help';help.textContent='Follow the connections to see how I use these skills together. Scroll horizontally to explore the tree.';document.querySelector('.map').after(help);
// Route the cross-branch link through the space between cards.
connections.querySelector('[data-from="scripting"][data-to="iac"]').setAttribute('d','M 288 275 H 318 V 185 H 616 V 90 H 628');
